default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3


test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  pool: 5
  encoding: unicode
  host: localhost
  port: 5432
  database: ask_me_prod
  user: ask_me
  password: <%= ENV["PASSWORD_DATABASE_USER"] %>
